spring:
  application:
    name: asrAgent
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=asr_agent
    username: postgres
    password: mysecret
  ai:
    dashscope:
      api-key: sk-355fdaeddf5743078b7d4c9efde61980
      chat:
        options:
          model: qwen3-max-2025-09-23
          multi-model: false
    vectorstore:
      pgvector:
        index-type: HNSW
      #  dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
        initialize-schema: true  # 核心配置：设为 true 即可自动建表
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  data:
    redis:
      host: localhost
      ttl: 3600
      port: 6379
      password:
server:
  port: 8123

asr:
  realtime:
    model: qwen3-asr-flash-realtime
    url: wss://dashscope.aliyuncs.com/api-ws/v1/realtime
translate:
  model: qwen-mt-flash
  api-key: sk-355fdaeddf5743078b7d4c9efde61980
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: my.asragent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: asrAgent
  public-endpoint: http://localhost:9000
logging:
  level:
    root: INFO
    my.asragent.service: DEBUG